[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
redb = "3.1.0"
ulid.workspace = true
chrono.workspace = true
thiserror.workspace = true

bytepack.workspace = true
db_core.workspace = true
query_parse.workspace = true